# Generated by Django 2.1.3 on 2018-11-11 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name that will be shown for the menu section', max_length=255, verbose_name='Title')),
                ('weight', models.IntegerField(default=0, help_text='The order to display the sections in. Smaller         numbers will appear first.', verbose_name='Weight')),
            ],
        ),
        migrations.CreateModel(
            name='Entree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the Entree', max_length=255, verbose_name='Title')),
                ('description', models.TextField(help_text='A description of the dish.', verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, help_text='The cost in dollars for the Entree.', max_digits=7, verbose_name='Price')),
                ('image', models.ImageField(blank=True, help_text='An image of the dish to show with         the description', null=True, upload_to='', verbose_name='Picture')),
                ('course', models.ForeignKey(help_text='The section of the menu the Entree will appear.', on_delete=django.db.models.deletion.CASCADE, to='restaurant.Course', verbose_name='Course')),
            ],
        ),
    ]
